x-rinhaquark2025: &rinhaquark2025
  image: kauanmocelin/rinhaquark2025:1.0.20
  environment:
    - QUARKUS_PAYMENTS_BATCH_SIZE=300
    - QUARKUS_PAYMENTS_BATCH_INTERVAL_MS=500
    - QUARKUS_PAYMENTS_THREADS_NUMBER=20
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - rinhaquark-rede
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.13"
        memory: "80MB"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx-loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinhaquark2025-a
      - rinhaquark2025-b
    networks:
      - rinhaquark-rede
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  rinhaquark2025-a:
    <<: *rinhaquark2025
    container_name: rinhaquark2025-a
    environment:
      - INTERNAL_SYNC_PAYMENTS_API=http://rinhaquark2025-b:8080

  rinhaquark2025-b:
    <<: *rinhaquark2025
    container_name: rinhaquark2025-b
    environment:
      - INTERNAL_SYNC_PAYMENTS_API=http://rinhaquark2025-a:8080

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - rinhaquark-rede
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "140MB"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payments_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - rinhaquark-rede

  prometheus-k1:
    image: prom/prometheus:v2.26.0
    container_name: prometheus-k1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - rinhaquark-rede
  grafana-k1:
    image: grafana/grafana-enterprise
    container_name: grafana-k1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus-k1
    networks:
      - rinhaquark-rede

volumes:
  pgadmin-data:

networks:
  rinhaquark-rede:
    driver: bridge
  payment-processor:
    external: true