services:

  nginx:
    image: nginx:alpine
    container_name: nginx-loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinhaquark2025-a
      - rinhaquark2025-b
    networks:
      - rinhaquark-rede
    mem_limit: 30m
    cpus: 0.2

  rinhaquark2025-a:
    image: kauanmocelin/rinhaquark2025:latest
    container_name: rinhaquark2025-a
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - rinhaquark-rede
      - payment-processor
    mem_limit: 70m
    cpus: 0.5

  rinhaquark2025-b:
    image: kauanmocelin/rinhaquark2025:latest
    container_name: rinhaquark2025-b
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - rinhaquark-rede
      - payment-processor
    mem_limit: 70m
    cpus: 0.5

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - rinhaquark-rede
    mem_limit: 180m
    cpus: 0.3
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  mongo-data:

networks:
  rinhaquark-rede:
    driver: bridge
  payment-processor:
    external: true