x-producer: &producer
  image: kauanmocelin/rinhaquark2025-producer:1.0.1
  depends_on:
    - redis
  networks:
    - rinhaquark-rede
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.2"
        memory: "40MB"

services:

  producer-a:
    <<: *producer
    container_name: producer-a

  producer-b:
    <<: *producer
    container_name: producer-b

  consumer:
    image: kauanmocelin/rinhaquark2025-consumer:1.0.1
    container_name: consumer
    environment:
      - QUARKUS_WORKER_SIZE=4
    depends_on:
      - redis
    networks:
      - rinhaquark-rede
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.1"
          memory: "40MB"

  nginx:
    image: nginx:alpine
    container_name: nginx-loadbalancer
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - producer-a
      - producer-b
    networks:
      - rinhaquark-rede
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    #    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - rinhaquark-rede
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - rinhaquark-rede
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - rinhaquark-rede

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - rinhaquark-rede

networks:
  rinhaquark-rede:
    driver: bridge
  payment-processor:
    external: true