global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'rinhaquark'
    scrape_interval: 5s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'producer-a:8080' ]
        labels:
          app: rinhaquark
          role: producer
          instance_name: producer-a

      - targets: [ 'producer-b:8080' ]
        labels:
          app: rinhaquark
          role: producer
          instance_name: producer-b

      - targets: [ 'consumer:8080' ]
        labels:
          app: rinhaquark
          role: consumer
          instance_name: consumer
